baseURL = 'https://blog.pybase.net'
languageCode = 'en-us'
title = 'Self learning AI resources. Python Tutorials and Machine Learning Devops. Django, Flask, FastAPI tutorials.'
theme = '2022'
ignoreFiles = ['\assets\node_modules\.*']
[params]
    name = "Pybase"
    description = "Education should be free for everyone. That's the main purpose of this blog."
    keywords = "Self learning AI resources, Python Tutorials, Machine Learning Devops"
    dateFormat = "2006-01-02 15:04:05"
    image = "/themes/2022/src/assets/images/logo.png"
    blog_pager = 10
    note_pager = 10
    article_pager = 10
    home_post_limit = 10
    GACode = "G-JX72TLXK4H"
    home_category_left = "python-tutorial"
    home_category_center = "ai"
    home_category_right = "cheatsheet"
    home_category_bottom = "frameworks"
    footer_tag_first_column = "artificial-intelligence"
    footer_tag_second_column = "python"
    footer_tag_third_column = "frameworks"
[taxonomies]
    category = "categories"
    tag = "tags"